ignored:
  - DL3007 # Example of ignoring a specific rule

override:  
  error:
    - DL3006 # Treat this rule as an error

  warning: [] # Empty array means treat no rules as warnings

  info: [] # Empty array means treat no rules as info