name: Lint Dockerfile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hadolint:
    name: Run Hadolint
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run Hadolint
        run: |
          docker run --rm -i hadolint/hadolint hadolint -t error - < Dockerfile