name: Lint Dockerfile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hadolint:
    name: Run Hadolint
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run Hadolint and Generate Report
        run: |
          docker run --rm -i -v $(pwd):/root hadolint/hadolint hadolint /root/Dockerfile - > hadolint-report.txt

      - name: Upload Hadolint Report
        uses: actions/upload-artifact@v2
        with:
          name: hadolint-report
          path: hadolint-report.txt